### ISSUE TITLE
Support for javascript Date as ql.start and ql.end, GROUP by time interval and nested functions

### ISSUE THREAD

**Issue by robertsLando** [vicanso/influx-ql#5]
Currently `ql.start` and `ql.end` don't work with javascript Date Object. I think it would be nice to add support for them, even if I pass a date string it isn't quoted in query result:

Javascript:
```
    var end = new Date();
    var start = new Date(Date.now() - (24*60*60*1000)); //last day
    var ql = new QL();
    ql.measurement = point.measurement;
    ql.addFunction('mean', 'value');
    ql.condition(point.tags);
    ql.start = start.toString();
    ql.end = end.toString();

    var query = ql.toSelect();

    console.log(query);
```

Output:

```
select mean("value") from "temperature" where ("location0" = 'garage' and "device" = '_thermo1') and time <= Thu Jan 25 2018 16:19:46 GMT+0100 (CET) and time >= Tue Jan 23 2018 04:19:46 GMT+0100 (CET)
```

There is also no support for [GROUP BY time intervals](https://docs.influxdata.com/influxdb/v0.9/query_language/data_exploration/#the-group-by-clause) (Example: GROUP BY time(interval[unit])) and for [nested functions](https://docs.influxdata.com/influxdb/v1.4/query_language/functions/#advanced-syntax-2) (Eample DIFFERENCE(first(value))

UPDATE:

At the moment I have been able to use Javascript dates by using a function to convert timestamp to nano string:

```
function dateToNano(date){
  return (date.getTime() * 1000000).toString();
}

......
    var end = new Date();
    var start = new Date(Date.now() - (24*60*60*1000)); //last day

    var ql = new QL();
    ql.measurement = point.measurement;
    ql.addFunction('mean', 'value');
    ql.condition(point.tags);
    ql.start = dateToNano(start);
    ql.end = dateToNano(end);

    var query = ql.toSelect();

```

**Comment by vicanso** [comment]
@robertsLando 

If you want to set the start at last day , you should use like this: 

```js
ql.start = '-24h';
```
The group by interval is supported by addGoup function, just like this:

```js
ql.measurement = 'http';
ql.start = '2016-04-01';
ql.end = '-3h';
ql.addFunction('count', 'code');
ql.addGroup('time(6h)');
```

And the nested function , you get the api from [API-addFunction](https://vicanso.github.io/influx-ql/QL.html#addFunction)

**Comment by robertsLando** [comment]
The start and end dates where just an example to show the problem, I don't unserstand why if I pass start.toString() to ql.start or ql.end it don't get quoted. I have solved the nested function and the group by time interval with your advices, thanks.

**Comment by vicanso** [comment]
@robertsLando 

I'm sorry, I misunderstood you question. I will fix it in the next version. But I had test in the influxdb, I found that it didn't support `Tue Jan 23 2018 04:19:46 GMT+0100 (CET)`. I suggest you use `toISOString` instead of `toString`.

Thanks for you comment

**Comment by robertsLando** [comment]
Thanks @vicanso for the quick reply and fix. 

I suggest you to add the group by time interval and the nested function examples on docs to make it more explicit, also a dedicated function could be really nice. 

This Influx query builder package is awesome! 👏🏻

**Comment by vicanso** [comment]
@robertsLando  I have improved the [document](https://vicanso.github.io/influx-ql/QL.html).
