### ISSUE TITLE
Composed Functions

### ISSUE THREAD

**Issue by ctaity** [vicanso/influx-ql#6]
Hi how can i do this query:

> select count(distinct(userId)) as value from heartbeat where time > now() - {} GROUP BY time({}) fill(0)

My porblem is with composed function:

>  count(distinct(userId))

**Comment by vicanso** [comment]
@ctaity  You can use like this `ql.addFunction('count', 'distinct("userId")');`

The API: https://vicanso.github.io/influx-ql/QL.html#addFunction

**Comment by digrich** [comment]
Adding the function like above gives the output as `select cumulative_sum("count("tid")")` instead of `select cumulative_sum(count("tid"))`. 
It adds double inverted commas to the inner function which actually fails the query. I am using 2.11.0 version.
