### ISSUE TITLE
Error when grouping by time with offset

### ISSUE THREAD

**Issue by robertsLando** [vicanso/influx-ql#7]
When grouping by time with an offset the query returns a error.
``` 
group by "time(86400s, 120m)"
ERR: difference aggregate requires a GROUP BY interval
```

If I remove the `" "` before and after the time parameter

```
group by time(86400s, 120m)
```

the query returns correctly.

When grouping by time without offset works even with `" "`

Influx Version  1.5.1

**Comment by vicanso** [comment]
I am sorry for late reply, please show me all codes that you have problem with.

**Comment by robertsLando** [comment]
```ql.addGroup(`time(${interval}s)`);```

Adds to the query `group by "time(86400s)"` and WORKS

```ql.addGroup(`time(${interval}s, ${gmtOffset}m)`);```

Adds to the query `group by "time(86400s, 120m)"` but this throws the error

`ERR: difference aggregate requires a GROUP BY interval`

**Comment by vicanso** [comment]
The function of group by time interval only supports one parameter, if you want to group by time interval and tags, you should use is like this:

```js
ql.addGroup('time(86400s)', 'spdy');
```

You can read [the document of influxdb group by time intervals](https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#group-by-time-intervals)

**Comment by robertsLando** [comment]
The second parameter allows to add an offset to the group by time. Check influx documentation about [group by time](https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#advanced-group-by-time-syntax). 

> time(time_interval,offset_interval)
>
>See the Basic GROUP BY time() Syntax for details on the time_interval.
>
>The offset_interval is a duration literal. It shifts forward or back InfluxDB’s preset time boundaries. The offset_interval can be positive or negative.

The strange thing here is that it works with double quotes with the basic group by time syntax and it doesn't works in the syntax with the offset.

**Comment by vicanso** [comment]
Sorry, I make a mistake. I will fix it asap.

**Comment by vicanso** [comment]
Please have a try the latest version
